package eum.backed.server.domain.community.avatar;

public enum AvatarLevelName {
    CLOUD_YOUNG,BABYSUN_YOUNG,SUN_YOUNG
    ,CLOUD_YOUTH,BABYSUN_YOUTH,SUN_YOUTH
    ,CLOUD_MIDDLE,BABYSUN_MIDDLE,SUN_MIDDLE
    ,CLOUD_OLD, BABAYSUN_OLD,SUN_OLD
    ,ORGANIZATION
}
