spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eum?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  ##
  redis:
    host : localhost
    port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect # 수정된 부분
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect # 중복 설정 제거
    generate-ddl: true
  sql:
    init:
      mode: always
jwt:
  header: Authorization
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
kakao :
  client-id: ${client-id}
  redirect-url: ${redirect-uri}
#firebase:
#  service-account-filename: src/main/resources/firebase.json
#  realtime-database-url: https://.firebaseio.com
